metadata:
  name: "ats-004-lab-082"
  docs:
    solution: "solution.md"
    question: "question.md"

runtime:
  type: "qemu"
  qemu:
  - image:
      type: "oci"
      source: "ghcr.io/astrona-io/ubuntu-qcow2-image:24.04-lfcs-{ARCH}"

    cpus: 2
    memoryMB: 2048
    diskSizeGB: 15
    display: false

bootstrap:
  init:
    - name: "lab-082-setup"
      description: "Prepares a directory with different symlinks pointing to various directories"
      type: "folder"
      source: "bootstrap/"

validation:
  scripts:
    - name: "verify-symlinks-audit"
      description: "Confirms proper scanning and resolving of symbolic links"
      type: "file"
      source: "validation/validate-completed.sh"

teardown:
  keepCluster: false
